### ISSUE TITLE
SfBadge is missing

### ISSUE THREAD

**Issue by gioboa** [thecoder93/storefront-qwik-boilerplate#1]
This is the react one 
https://github.com/vuestorefront/storefront-ui/blob/v2/packages/sfui/frameworks/react/components/SfBadge/SfBadge.tsx

**Comment by thecoder93** [comment]
Is it already available on qwik-storefront-ui?

**Comment by gioboa** [comment]
No, the badge component is missing. We need to convert the react one in Qwik ( in this repo )
You can check the link I posted.
Would you like to drop a PR for that?

**Comment by thecoder93** [comment]
Ok, but why we need to convert in this repo? 🤔  Here we use, for example SfButton or SfSelect from qwik-storefront library.
Anyway, I try to drop a PR.

**Comment by gioboa** [comment]
You are right, this is the wrong repo 🤣😅

**Comment by gioboa** [comment]
I recreate the issue in the right repo --> https://github.com/qwikifiers/qwik-storefront-ui/issues/7
